import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.tsx';
import './index.css';
import { AuthProvider } from './context/AuthContext.tsx';
import { ThemeProvider } from './context/ThemeContext.tsx';
import { FinanceProvider } from './context/FinanceContext.tsx';
// @ts-ignore — virtual module provided by vite-plugin-pwa at build time
import { registerSW } from 'virtual:pwa-register';

// Registers the service worker generated by vite-plugin-pwa. This caches the app shell
// (JS/CSS/HTML/icons/fonts) so Expenzo can be opened from the home screen with zero
// connectivity, instead of Safari showing "can't open the page." `onNeedRefresh` fires
// when a new deployed version is available in the background — the app auto-updates to it
// on the next load rather than getting stuck showing an old cached version indefinitely.
if ('serviceWorker' in navigator) {
  registerSW({
    immediate: true,
    onRegisteredSW(swUrl: string) {
      console.log('Service worker registered for offline use:', swUrl);
    },
    onRegisterError(error: any) {
      console.warn('Service worker registration failed — offline mode unavailable:', error);
    },
  });
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <ThemeProvider>
      <AuthProvider>
        <FinanceProvider>
          <App />
        </FinanceProvider>
      </AuthProvider>
    </ThemeProvider>
  </React.StrictMode>,
);
